name: Build Pipeline
on:
    push:
        branches:
            - development
            - add-github-actions-support
        paths-ignore:
            - ".clang-format"
            - ".clang-tidy"
            - ".editorconfig"
            - ".gitignore"
            - "README.md"
    pull_request:
        branches:
            - development
        paths-ignore:
            - ".clang-format"
            - ".clang-tidy"
            - ".editorconfig"
            - ".gitignore"
            - "README.md"
jobs:
    build:
        env:
            CMAKE_BUILD_TYPE: RelWithDebInfo
            CMAKE_GENERATOR: Ninja
            VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
            VCPKG_DISABLE_METRICS: ON
        strategy:
            matrix:
                os: [ ubuntu-latest ]
                include:
                    -   os: "ubuntu-latest"
                        triplet: "x64-linux"
                        mono: "mono"
        runs-on: ${{ matrix.os }}
        defaults:
            run:
                shell: bash
        steps:
            -   name: Install doxygen
                run: |
                    sudo apt-get update
                    sudo apt-get install doxygen ninja-build
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: "Setup NuGet Credentials"
                run: >
                    ${{ matrix.mono }} `$VCPKG_INSTALLATION_ROOT/vcpkg fetch nuget | tail -n 1`
                    sources add
                    -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
                    -storepasswordincleartext
                    -name "GitHub"
                    -username "${{ github.repository_owner }}"
                    -password "${{ secrets.GITHUB_TOKEN }}"
            -   name: Debug information
                run: |
                    ls -al
                    env | sort
            -   name: Configure
                run: cmake -B .build -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }}
            -   name: Build
                run: cmake --build .build
